name: Generate Stats Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      EXCLUDED: github-stats
      EXCLUDED_LANGS: ""
      COUNT_STATS_FROM_FORKS: ""
    
    steps:
      # Checkout your repository
      - uses: actions/checkout@v4

      # Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      # Cache pip dependencies for faster builds
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      # Generate SVG images
      - name: Generate images
        run: |
          python3 --version
          python3 generate_images.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          EXCLUDED: github-stats
          EXCLUDED_LANGS: ""
          COUNT_STATS_FROM_FORKS: ""

      # Commit generated images to the output branch
      - name: Commit to output branch
        run: |
          git config --global user.name "github-stats[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m 'temp commit' || echo
          git checkout output 2>/dev/null || git checkout --orphan output && git rm -rf . && git checkout main -- generated/
          git commit -m 'Update generated files' || echo
          git push origin output -f
